print("Witaj w Życzeniomacie!")
print("Ten program wygeneruje dla Ciebie krótkie życzenia urodzinowe.\nW kolejnych krokach postępuj zgodnie z poleceniami:\n")
print("Podaj dzisiejszą datę:\nDzień/Miesiąc...:") 
data_dzien = input()
print("...oraz rok")
data_rok = int(input())
print("Podaj swoje imię:") 
imie_nadawcy = input()
print("Podaj imię jubilat/ka:")
imie_odbiorcy = input()
print("Podaj rok urodzenia jubilata/ki:")
data_urodzenia = int(input())
print("Dokończ zdanie: życzę Ci...")
zyczenia = input()
wiek = (data_rok - data_urodzenia)
print("\n __________________________________________________________________________________________<3\n|")
print(f"|Witaj {imie_odbiorcy}!\n|\n|Z okazji Twoich {wiek} urodzin, życzę Ci {zyczenia}!\n|\n|~{imie_nadawcy}!")
print("|__________________________________________________________________________________________<3\n")
#ver1.1